### ISSUE TITLE
Implement non scripted approach

### ISSUE THREAD

**Issue by lukehinds** [StacklokLabs/promptwright#10]
Users can leverage a YAML file that conforms with promptwright values and results in no need to develop a script, for example (to spitball)

```yaml
system_prompt: "You are a creative writing instructor providing writing prompts and example responses. If you use apostrophes in your prompts, make sure to escape them with a backslash. For example, use 'don\'t' instead of 'don't'. Respond only with valid JSON. Do not write an introduction or summary."
tree:
  root_prompt: "Creative Writing Prompts"
  tree_degree: 5
  tree_depth: 4
  model_name: "ollama/llama3.2"
  tree_save: "my_topictree.jsonl"

dataset:
  instructions: "Generate creative writing prompts and example responses."
  system_prompt: "system_prompt"
  model_name: "ollama/llama3.2"
  temperature: 10
  num_steps: 100
  batch_size: 10
  topic_tree: "tree"
  dataset_save: "creative_writing.jsonl"
```
